site_name: SWA mkdocs
site_description: 'A mkdocs test'
site_author: 'Philip Affolter'
docs_dir: docs/
repo_name: 'philippaffolter/swa'
repo_url: 'https://github.com/philippaffolter/swa'
nav:
    - Home: index.md
theme:
  name: 'material'
